### ISSUE TITLE
Does DontEatMyContent support Sideloading? [Error Problems?]

### ISSUE THREAD

**Issue by arichorn** [therealFoxster/DontEatMyContent#1]
hello therealFoxstee! I recently tried using this for sideloading in my version of uYouPlus!(forked) but I had problems with it and tried building the ipa 8 times with it and all it says is this error from the tweak. 
**error: fell off the face of the planet when we found a '}'**
 I did try to fix it but removing a few bits of code will mess your wonderful tweak. I tried implementing it because my iPhone does play content in the notch.
![43BEFCAA-004F-41FA-88EC-408D1710501B](https://user-images.githubusercontent.com/78001398/192008677-b400bed2-ac13-464c-996d-7aceeba3b09c.jpeg)
and here’s the code I tried to implement. And it is a bit modified so it’ll work as a toggleable option in settings.
```
%group gDontEatMyContent
%hook YTPlayerViewController

- (void)viewDidAppear:(BOOL)animated {
    YTPlayerView *playerView = [self playerView];
    UIView *renderingViewContainer = MSHookIvar<UIView *>(playerView, "_renderingViewContainer");
    renderingView = [playerView renderingView];

    CGFloat constant = 23; // Make renderingView a bit larger since safe area has sizeable margins from the notch and side borders; tested on iPhone 13 mini

    widthConstraint = [renderingView.widthAnchor constraintEqualToAnchor:renderingViewContainer.safeAreaLayoutGuide.widthAnchor constant:constant];
    heightConstraint = [renderingView.heightAnchor constraintEqualToAnchor:renderingViewContainer.safeAreaLayoutGuide.heightAnchor constant:constant];
    centerXConstraint = [renderingView.centerXAnchor constraintEqualToAnchor:renderingViewContainer.centerXAnchor];
    centerYConstraint = [renderingView.centerYAnchor constraintEqualToAnchor:renderingViewContainer.centerYAnchor];
    
    // playerView.backgroundColor = [UIColor greenColor];
    // renderingViewContainer.backgroundColor = [UIColor redColor];
    // renderingView.backgroundColor = [UIColor blueColor];

    YTMainAppVideoPlayerOverlayViewController *activeVideoPlayerOverlay = [self activeVideoPlayerOverlay];

    // Must check class since YTInlineMutedPlaybackPlayerOverlayViewController doesn't have -(BOOL)isFullscreen
    if ([NSStringFromClass([activeVideoPlayerOverlay class]) isEqualToString:@"YTMainAppVideoPlayerOverlayViewController"] && [activeVideoPlayerOverlay isFullscreen]) {
        activate();
    } else {
        center();
    }
    %orig(animated);
}
- (void)didPressToggleFullscreen {  
    YTMainAppVideoPlayerOverlayViewController *activeVideoPlayerOverlay = [self activeVideoPlayerOverlay];
    
    if (![activeVideoPlayerOverlay isFullscreen]) // Entering fullscreen
        activate();
    else // Exiting fullscreen
        deactivate();
    
    %orig;
}
- (void)didSwipeToEnterFullscreen { 
    %orig; activate(); 
}
- (void)didSwipeToExitFullscreen { 
    %orig; deactivate();
}
- (void)singleVideo:(id)arg1 aspectRatioDidChange:(CGFloat)arg2 {
    aspectRatio = arg2;
    if (aspectRatio == 0.0) { 
        // App backgrounded
    } else if (aspectRatio < THRESHOLD) {
        deactivate();
    } else {
        activate();
    }
    %orig(arg1, arg2);
}
%end

%hook YTVideoZoomOverlayView
- (void)didRecognizePinch:(UIPinchGestureRecognizer *)pinchGestureRecognizer {
    // %log((CGFloat) [pinchGestureRecognizer scale], (CGFloat) [pinchGestureRecognizer velocity]);
    if ([pinchGestureRecognizer velocity] <= 0.0) { // >>Zoom out<<
        zoomedToFill = false;
        activate();
    } else if ([pinchGestureRecognizer velocity] > 0.0) { // <<Zoom in>>
        zoomedToFill = true;
        deactivate();
    }

    %orig(pinchGestureRecognizer);
}
- (void)flashAndHideSnapIndicator {}

// https://github.com/lgariv/UniZoom/blob/master/Tweak.xm
- (void)setSnapIndicatorVisible:(bool)arg1 {
    %orig(NO);
}
%end
%end
```

**Comment by therealFoxster** [comment]
The error is indicating that an extra close curly bracket ("`}`") was found. I just looked at your [uYouPlus.xm](https://github.com/arichorn/uYouPlusExtra/blob/main/uYouPlus.xm) file and there seems to be a missing open curly bracket ("`{`") on line 1158: 

`if (dontEatMyContent)` **`{`**. 

Adding it should resolve the issue. Let me know if you're still having problems!

**Comment by arichorn** [comment]
I might’ve forgot to add that, I sometimes forget the code at the bottom but at the moment I am having errors because your tweak uses a lot of unused YouTubeHeaders in uYouPlus and I’m currently trying to sort it out rn

**Comment by therealFoxster** [comment]
My function and interface declarations are in the [Tweak.h](https://github.com/therealFoxster/DontEatMyContent/blob/master/Tweak.h) file. I could and should have put them in proper individual header files but I didn't :P. Make sure you have those in your header file as well.

**Comment by arichorn** [comment]
Alright I’ll see if adding of these should work, I tell you when it works (or a chance of it not working)

**Comment by arichorn** [comment]
I’m back. I did fix a lot of errors with the YouTubeHeaders but after 2 hours of fixing I still get the unsuccessful action build error but yeah since I’m not a full-on expert on coding I always fail on doing something successful.
https://github.com/arichorn/uYouPlusExtra/actions/runs/3116229693/jobs/5053874968

**Comment by therealFoxster** [comment]
It seems like the functions hasn't been declared. If you're including the YouTube header files manually, you must also include all of their superclasses' header files as well (the superclasses will have the required function declarations), which would require a lot of work. Your best bet, like I said, would be to copy the interface and function declarations from my [Tweak.h](https://github.com/therealFoxster/DontEatMyContent/blob/master/Tweak.h) file to your header file.

**Comment by arichorn** [comment]
Hey I’m back! And good news! It built the app without any consequences! I was happy when it successfully builded the ipa. If you go to my uYouPlus fork, then the branch with all those commits will be resettled.
but overrall it worked! 
here’s the ipa if you want to see! https://github.com/arichorn/uYouPlusExtra/releases/download/v17.37.3-2.1-(207)/uYouPlusExtra_17.37.3_2.1_F4.ipa

**Comment by arichorn** [comment]
Also my iPhone doesn’t show the option so I gotta say nice job on adding the unsupported device feature!

**Comment by therealFoxster** [comment]
Which iPhone do you have?

**Comment by arichorn** [comment]
I can see the option now, the reason why it was invisible was because me not including the tweak in the NSMutableArray but since I added it, it is visible.

> Which iPhone do you have?

My model is the iPhone 11 (Non-Pro)

**Comment by therealFoxster** [comment]
That's a bit strange, because the tweak should not run on your device. It only supports iPhone 12 mini, iPhone 13 series and newer. You don't need the tweak anyway, since the notch doesn't cut into 2:1 videos on your device.

**Comment by arichorn** [comment]
> That's a bit strange, because the tweak should not run on your device. It only supports iPhone 12 mini, iPhone 13 series and newer. You don't need the tweak anyway, since the notch doesn't cut into 2:1 videos on your device.

yep, but I didn’t just add this tweak for me, I added it to my repository for everyone else that uses iPhone 12 Mini and newer. So definitely did something helpful for ya ✌️

**Comment by therealFoxster** [comment]
I see. It's still weird that it shows up on your device. Hopefully it doesn't act up or do something weird (it shouldn't in most cases).
